config/routes.rb
Rails.application.routes.draw do
  resources :bowlings do
    member do
      get :get_strings_of, :add_two_rolls
    end
  end

end

app/models/bowling.rb
class Bowling < ActiveRecord::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bowlings_controller.rb
class BowlingsController < ApplicationController
  before_action :set_bowling, only: [:add_two_rolls, :show, :edit, :update, :destroy]


  # GET /bowlings
  # GET /bowlings.json
  def index
    @bowlings = Bowling.all
  end

  # GET /bowlings/1
  # GET /bowlings/1.json
  def show
  end

  # GET /bowlings/new
  def new
    @bowling = Bowling.new
  end

  # GET /bowlings/1/edit
  def edit
  end

  # POST /bowlings
  # POST /bowlings.json
  def create
    @bowling = Bowling.new(bowling_params)

    respond_to do |format|
      if @bowling.save
        format.html { redirect_to @bowling, notice: 'Bowling was successfully created.' }
        format.json { render :show, status: :created, location: @bowling }
      else
        format.html { render :new }
        format.json { render json: @bowling.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bowlings/1
  # PATCH/PUT /bowlings/1.json
  def update
    respond_to do |format|
      if @bowling.update(bowling_params)
        format.html { redirect_to @bowling, notice: 'Bowling was successfully updated.' }
        format.json { render :show, status: :ok, location: @bowling }
      else
        format.html { render :edit }
        format.json { render json: @bowling.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bowlings/1
  # DELETE /bowlings/1.json
  def destroy
    @bowling.destroy
    respond_to do |format|
      format.html { redirect_to bowlings_url, notice: 'Bowling was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bowling
      @bowling = Bowling.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bowling_params
      params.require(:bowling).permit(:score, :first_roll, :second_roll)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bowlings_helper.rb
module BowlingsHelper

end

app/views/bowlings/_form.html.erb
<%= form_for(@bowling) do |f| %>
  <% if @bowling.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bowling.errors.count, "error") %> prohibited this bowling from being saved:</h2>

      <ul>
      <% @bowling.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :first_roll %><br>
    <%= f.number_field :first_roll %>
  </div>
  <div class="field">
    <%= f.label :second_roll %><br>
    <%= f.number_field :second_roll %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bowlings/edit.html.erb
<h1>Editing Bowling</h1>

<%= render 'form' %>

<%= link_to 'Show', @bowling %> |
<%= link_to 'Back', bowlings_path %>

app/views/bowlings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ten Pin Bowling Score</h1>

  <% rolls = '6 2 7 1 10 9 0 8 2 10' %>
  <% @array = [] %>
  <% 0.upto(rolls.length - 1) do |num| %>
    <% if rolls.at(num) != ' ' %>
      <% first = rolls.at(num) %>
      <% if rolls.at(num + 1) != ' ' %>
        <% second = rolls.at(num + 1) %>
        <% combined = (first.to_s) + (second.to_s) %>
        <% if combined != '' %> <%# filter out empty character %>
          <% @array << combined.to_i %>
        <% end %>
        <% rolls.slice!(num + 1) %><%# delete the 2nd digit if it is 10 %>
      <% else %>
        <% @array << first.to_i %>
      <% end %>
    <% end %>
  <% end %>

  <% @score = 0 %>
  <% 0.upto(@array.length - 1) do |num| %>
    <% if @array[num] != 10 %>
      <% if (@array[num].to_i + @array[num + 1].to_i) != 10 %><%# if normal scoring, not Strike, not Spare %>
        <% @score += (@array[num].to_i + @array[num + 1].to_i) %>
        <% @array.delete_at(num + 1) %><%# delete the second roll of the normal scoring %>
      <% elsif (@array[num].to_i + @array[num + 1].to_i) == 10 %><%# if hits the Spare %>
        <% @score += 10 %>
        <% @array.delete_at(num + 1) %><%# delete the second roll of score 10 %>
        <% if @array[num + 1].present? %><%# if we know the next one roll %>
          <% @score += @array[num + 1].to_i %>
        <% end %>
      <% end %>
    <% elsif @array[num] == 10 %>
      <% if (@array[num + 1].present?) && (@array[num + 2].present?) %>
        <% @score += 10 + @array[num + 1].to_i + @array[num + 2].to_i %>
      <% end %>
    <% end %>
  <% end %>

  '<%= rolls %>' -> <%= @score %>
</p>

app/views/bowlings/new.html.erb
<h1>New Bowling</h1>

<%= render 'form' %>

<%= link_to 'Back', bowlings_path %>

app/views/bowlings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Score:</strong>
  <%= @bowling.score %>
</p>

<p>
  <strong>First roll:</strong>
  <%= @bowling.first_roll %>
</p>

<p>
  <strong>Second roll:</strong>
  <%= @bowling.second_roll %>
</p>

<%= link_to 'Edit', edit_bowling_path(@bowling) %> |
<%= link_to 'Back', bowlings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyTEst</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>